#!/usr/bin/env bash
echo "put object $1"

# check if at least 1 argument is provided
if [ -z "$1" ]; then  # use -z instead of [ "$#" -eq 0 ] to check for empty string
    echo "No bucket name provided"
    exit 1
fi

# check for file name
if [ -z "$2" ]; then  # use -z instead of [ "$#" -eq 0 ] to check for empty string
    echo "No file name provided"
    exit 1
fi

BUCKET_NAME="$1"
FILE_NAME="$2"

OBJECT_KEY=$(basename "$FILE_NAME") # get the file name from the path

aws s3api put-object \
  --bucket "$BUCKET_NAME" \
  --key "$OBJECT_KEY" \
  --body "$FILE_NAME"