AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: SNS Basic Setup

Resources:
  MyTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: my-sns-topic

  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: python3.9
      PackageType: Zip
      InlineCode: |
        import json

        def handler(event, context):
            print("Received event: " + json.dumps(event, indent=2))
            return {
                'statusCode': 200,
                'body': json.dumps('Hello from Lambda!')
            }
      Events:
        MySNSTopic:
          Type: SNS
          Properties:
            Topic: !Ref MyTopic

Outputs:
  MyTopicArn:
    Description: SNS topic ARN
    Value: !Ref MyTopic
