AWSTemplateFormatVersion: 2010-09-09
Description: A simple S3 bucket
Resources:
  S3Bucket: # name whatever you like
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName: example-bucket-newnew-cw888